//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ten kod źródłowy został wygenerowany automatycznie przez Microsoft.VSDesigner, wersja 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication.myservicewebreference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllPeopleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOsobaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOsobaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveOsobaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WebApplication.Properties.Settings.Default.WebApplication_myservicewebreference_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllPeopleCompletedEventHandler GetAllPeopleCompleted;
        
        /// <remarks/>
        public event GetOsobaCompletedEventHandler GetOsobaCompleted;
        
        /// <remarks/>
        public event AddOsobaCompletedEventHandler AddOsobaCompleted;
        
        /// <remarks/>
        public event RemoveOsobaCompletedEventHandler RemoveOsobaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPeople", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] GetAllPeople() {
            object[] results = this.Invoke("GetAllPeople", new object[0]);
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPeopleAsync() {
            this.GetAllPeopleAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPeopleAsync(object userState) {
            if ((this.GetAllPeopleOperationCompleted == null)) {
                this.GetAllPeopleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPeopleOperationCompleted);
            }
            this.InvokeAsync("GetAllPeople", new object[0], this.GetAllPeopleOperationCompleted, userState);
        }
        
        private void OnGetAllPeopleOperationCompleted(object arg) {
            if ((this.GetAllPeopleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPeopleCompleted(this, new GetAllPeopleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOsoba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person GetOsoba(int id) {
            object[] results = this.Invoke("GetOsoba", new object[] {
                        id});
            return ((Person)(results[0]));
        }
        
        /// <remarks/>
        public void GetOsobaAsync(int id) {
            this.GetOsobaAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOsobaAsync(int id, object userState) {
            if ((this.GetOsobaOperationCompleted == null)) {
                this.GetOsobaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOsobaOperationCompleted);
            }
            this.InvokeAsync("GetOsoba", new object[] {
                        id}, this.GetOsobaOperationCompleted, userState);
        }
        
        private void OnGetOsobaOperationCompleted(object arg) {
            if ((this.GetOsobaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOsobaCompleted(this, new GetOsobaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOsoba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] AddOsoba(string imie, string nazwisko) {
            object[] results = this.Invoke("AddOsoba", new object[] {
                        imie,
                        nazwisko});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void AddOsobaAsync(string imie, string nazwisko) {
            this.AddOsobaAsync(imie, nazwisko, null);
        }
        
        /// <remarks/>
        public void AddOsobaAsync(string imie, string nazwisko, object userState) {
            if ((this.AddOsobaOperationCompleted == null)) {
                this.AddOsobaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOsobaOperationCompleted);
            }
            this.InvokeAsync("AddOsoba", new object[] {
                        imie,
                        nazwisko}, this.AddOsobaOperationCompleted, userState);
        }
        
        private void OnAddOsobaOperationCompleted(object arg) {
            if ((this.AddOsobaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOsobaCompleted(this, new AddOsobaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveOsoba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] RemoveOsoba(int id) {
            object[] results = this.Invoke("RemoveOsoba", new object[] {
                        id});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void RemoveOsobaAsync(int id) {
            this.RemoveOsobaAsync(id, null);
        }
        
        /// <remarks/>
        public void RemoveOsobaAsync(int id, object userState) {
            if ((this.RemoveOsobaOperationCompleted == null)) {
                this.RemoveOsobaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveOsobaOperationCompleted);
            }
            this.InvokeAsync("RemoveOsoba", new object[] {
                        id}, this.RemoveOsobaOperationCompleted, userState);
        }
        
        private void OnRemoveOsobaOperationCompleted(object arg) {
            if ((this.RemoveOsobaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveOsobaCompleted(this, new RemoveOsobaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Person {
        
        private int idField;
        
        private string imięField;
        
        private string nazwiskoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Imię {
            get {
                return this.imięField;
            }
            set {
                this.imięField = value;
            }
        }
        
        /// <remarks/>
        public string Nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                this.nazwiskoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAllPeopleCompletedEventHandler(object sender, GetAllPeopleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPeopleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPeopleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOsobaCompletedEventHandler(object sender, GetOsobaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOsobaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOsobaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddOsobaCompletedEventHandler(object sender, AddOsobaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOsobaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOsobaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveOsobaCompletedEventHandler(object sender, RemoveOsobaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveOsobaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveOsobaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591