const API_BASE_DEVELOPMENT = "https://localhost:7156";

const ENDPOINTS ={
    GET_ALL_USERS: 'get-all-users',
    GET_POSTS_BY_ID: 'get-users-by-id',
    CREATE_USER: 'create-users',
    UPDATE_USER: 'update-users',
    DELETE_POST_BY_ID: 'delete-post-by-id'
};

const development = {
    API_URL_GET_ALL_USERS: `${API_BASE_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_DEVELOPMENT}/${ENDPOINTS.GET_POSTS_BY_ID}`,
    API_URL_GET_UPDATE_USER: `${API_BASE_DEVELOPMENT}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_GET_DELETE_USER: `${API_BASE_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`,
}

