//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImięField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwiskoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Imię {
            get {
                return this.ImięField;
            }
            set {
                if ((object.ReferenceEquals(this.ImięField, value) != true)) {
                    this.ImięField = value;
                    this.RaisePropertyChanged("Imię");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nazwisko {
            get {
                return this.NazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwiskoField, value) != true)) {
                    this.NazwiskoField = value;
                    this.RaisePropertyChanged("Nazwisko");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetAllPeopleResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        WebApplication.ServiceReference1.GetAllPeopleResponse GetAllPeople(WebApplication.ServiceReference1.GetAllPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.ServiceReference1.GetAllPeopleResponse> GetAllPeopleAsync(WebApplication.ServiceReference1.GetAllPeopleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeople", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.ServiceReference1.GetAllPeopleRequestBody Body;
        
        public GetAllPeopleRequest() {
        }
        
        public GetAllPeopleRequest(WebApplication.ServiceReference1.GetAllPeopleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPeopleRequestBody {
        
        public GetAllPeopleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeopleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.ServiceReference1.GetAllPeopleResponseBody Body;
        
        public GetAllPeopleResponse() {
        }
        
        public GetAllPeopleResponse(WebApplication.ServiceReference1.GetAllPeopleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPeopleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Person[] GetAllPeopleResult;
        
        public GetAllPeopleResponseBody() {
        }
        
        public GetAllPeopleResponseBody(WebApplication.ServiceReference1.Person[] GetAllPeopleResult) {
            this.GetAllPeopleResult = GetAllPeopleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebApplication.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebApplication.ServiceReference1.WebServiceSoap>, WebApplication.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServiceReference1.GetAllPeopleResponse WebApplication.ServiceReference1.WebServiceSoap.GetAllPeople(WebApplication.ServiceReference1.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeople(request);
        }
        
        public WebApplication.ServiceReference1.Person[] GetAllPeople() {
            WebApplication.ServiceReference1.GetAllPeopleRequest inValue = new WebApplication.ServiceReference1.GetAllPeopleRequest();
            inValue.Body = new WebApplication.ServiceReference1.GetAllPeopleRequestBody();
            WebApplication.ServiceReference1.GetAllPeopleResponse retVal = ((WebApplication.ServiceReference1.WebServiceSoap)(this)).GetAllPeople(inValue);
            return retVal.Body.GetAllPeopleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServiceReference1.GetAllPeopleResponse> WebApplication.ServiceReference1.WebServiceSoap.GetAllPeopleAsync(WebApplication.ServiceReference1.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeopleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServiceReference1.GetAllPeopleResponse> GetAllPeopleAsync() {
            WebApplication.ServiceReference1.GetAllPeopleRequest inValue = new WebApplication.ServiceReference1.GetAllPeopleRequest();
            inValue.Body = new WebApplication.ServiceReference1.GetAllPeopleRequestBody();
            return ((WebApplication.ServiceReference1.WebServiceSoap)(this)).GetAllPeopleAsync(inValue);
        }
    }
}
